languages:
  JavaScript: true

exclude_paths:
- "checkstyle/**"
- "coverage/**"
- "dist/**/*"
- "gulp/**/*"
- "gulpfile.js"

ratings:
  paths:
  - "src/**"
  - "test/**"

engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript