exclude_paths:
- "checkstyle/**"
- "coverage/**"
- "node_modules/**"
- "esdoc/**"
- "./*.js"
- "dist/**/*"
- "dist/reach.js"
- "dist/reach-debug.js"
- "test/**.js"
- ".*/"

ratings:
  paths:
  - "src/**.js"

engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: "./.eslintrc.yml"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
